server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sm?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: d7b42182abb7a263c012e30edc19cbee
            client-secret: SjUpGjb2r16QV62kXsUx5avZOWYFNOlZ
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
mybatis:
  type-aliases-package: com.example.web01.app.dto
  mapper-locations: classpath:/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
logging:
  level:
    root: info